### ISSUE TITLE
include roofs error

### ISSUE THREAD

**Issue by biglimp** [jixuan-chen/target#11]
I am still getting errors for a missing key:

```
Traceback (most recent call last):
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\target_algorithm.py", line 242, in processAlgorithm
tar.run_simulation(save_csv=False)
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\target_py\scripts\toolkit.py", line 444, in run_simulation
ta_rslts = calc_ta(self.parameters, self.cfM, lc_data, grid, i, met_d, z_Uref, z_Hx2, Tb_rur, mod_data_ts_,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\OSGeo4W\apps\Python312\Lib\site-packages\target_py\scripts\Ta_module_new.py", line 124, in calc_ta
if cfM['include roofs'] == "Y":
~~~^^^^^^^^^^^^^^^^^
KeyError: 'include roofs'
```
Is this mandatory in config.ini and if so, what is the syntax since there is a space in the variable?

**Comment by biglimp** [comment]
I fixed it but it looks like `include roofs` is mandatory, at least for me. Maybe this should be added into the test datasets...

**Comment by jixuan-chen** [comment]
Yes, it is mandatory at the moment, but I wanted to discuss what parameters we'd like to make adjustable to the users. 
The Java version allows overriding a few parameters in the config file, including 
- roughness length `z0m_rur` and surface type `ref_surf` of` the rural site 
- reference heights for windspeed and air temperature measurements `z_URef` and `z_TaRef`
- domain average building height `zavg` 
Users also have the option to 
- disable unwanted outputs with `disableOutput`
- turn roofs on and off to affect Tac with `include roofs` (I think it's done to allow for the possibility of modelling green roofs, but there is no simple switch for the user to turn the roofs to green in the model yet.)
- use modelled incoming longwave radiation with `mod_ldwn`

Do we want to keep the Umep version consistent with the Java version in this regard? Or will it be challenging for setting up pre and post analysis tools (e.g. with changing output)? 
To me some parameters (e.g. reference heights) are important to include and some (e.g. include roofs) should have a default value or maybe just be excluded to not scare the users with too many input fields.
Let me what you think and I can release a new PyPI version!

**Comment by biglimp** [comment]
Have you tested to see the impact of some of the parameters, e.g. `z0m_rur` `ref_surf` and `zavg`? 

I guess `zavg` should be retrieved from the input land cover file (mean of H) and not be a separate input. 

As reference heights (I assume above ground) is standard, so users should not set these.

**Comment by jixuan-chen** [comment]
Nope, but I can have a look next week.

I agree that zavg should be just calculated from the input data and that's what I've been doing... no idea why it's always kept in the list but I've been trying to just keep the model as it is. 

For Zurich the wind speed data we used (which is from a "standard" weather station) were taken at 28m... maybe it's a very rare case. (Just a random thought, maybe we can have an "Advanced settings" button?)

Will get back to you next week.
