### ISSUE TITLE
Use test cases possible bugs

### ISSUE THREAD

**Issue by ebocher** [jixuan-chen/target#14]
Hi,

Thank you for the development of this tool. 
We have completed the construction of the landt grid from GeoClimate output (see https://github.com/orbisgis/geoclimate/pull/1008).

Sometimes TARGET works well, sometimes not.

In this issue we propose to share some of the potential bugs we have identified.

**Comment by ebocher** [comment]
**Data input** 
[target_data_config.zip](https://github.com/user-attachments/files/18023629/target_data_config.zip)

**Target command** 

```
python3 -m target_py run -c config.ini --save-csv
```


Return

```
[2024-12-05 12:20:42 - INFO] - loading config
[2024-12-05 12:20:42 - INFO] - running simulation
  0%|                                                    | 0/73 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ebocher/.local/lib/python3.10/site-packages/target_py/__main__.py", line 30, in <module>
    tar.run_simulation(save_csv=args.save_csv)
  File "/home/ebocher/.local/lib/python3.10/site-packages/target_py/scripts/toolkit.py", line 444, in run_simulation
    ta_rslts = calc_ta(self.parameters, self.cfM, lc_data, grid, i, met_d, z_Uref, z_Hx2, Tb_rur, mod_data_ts_,
  File "/home/ebocher/.local/lib/python3.10/site-packages/target_py/scripts/Ta_module_new.py", line 42, in calc_ta
    lc_stuff = lc_sort(cs, LC, H, W)
  File "/home/ebocher/.local/lib/python3.10/site-packages/target_py/scripts/LcSort.py", line 142, in lc_sort
    'H': H, 'W': W, 'Wtree': Wtree, 'fw': fw, 'fg':fg, 'svfwA': svfwA, 'svfgA': svfgA}
UnboundLocalError: local variable 'fg' referenced before assignment
```

**Comment by ebocher** [comment]
A new use case that returns -999 for variables Ta, Tmrt, UTCI and UTCI_cat.

See input data
[my_site2.zip](https://github.com/user-attachments/files/18065193/my_site2.zip)

**Comment by jixuan-chen** [comment]
Hi, this is because the grid cell has a roof fraction > 75%. In this case
the model won’t calculate air temperature and so on.

**Comment by ebocher** [comment]
> Hi, this is because the grid cell has a roof fraction > 75%. In this case the model won’t calculate air temperature and so on.

Thanks.

Do you have any ideas or comments about the first case?

**Comment by jixuan-chen** [comment]
Hi,

I don't have the chance to run the model with your data but I looked over
your LC input and it seems your W is problematic.

W is the average canyon (street) width calculated from the building layout.

The spatial resolution is 30 m (you can change  "res" to match your case in
parameters), meaning that the max. W is 30 m, but you have W values up to
122984.

**Comment by ebocher** [comment]
Thanks @jixuan-chen 

Not sure to understand.

What do you mean about 30 m resolution. My LC grid has been compute over a 100*100 meters UTM and then reprojected in 4326.
Approximately : 
latResolution=0.0009152141023989202
lonResolution=0.0013423499309754838

and thank you for your great work

**Comment by jixuan-chen** [comment]
In parameters.json or in generate.py, depending on how you run the model,
there is a parameter "res" which is the resolution of the grid and you need
to change it to 100 according to your data.

I'll make it overridable in the config file in the next release.

So your grid has a resolution of 100m if I understand correctly, then how
can you have a street width of over 100000m? The model generalizes the
urban environment to an idealized urban canyon (buildings on two sides,
check Fig.1 in the paper <https://gmd.copernicus.org/articles/12/785/2019/>
).

**Comment by ebocher** [comment]
> In parameters.json or in generate.py, depending on how you run the model, there is a parameter "res" which is the resolution of the grid and you need to change it to 100 according to your data.

Thanks I will fix it.



> So your grid has a resolution of 100m if I understand correctly, then how can you have a street width of over 100000m?

ouppsss
very strange indeed. I'll check the GeoClimate algo

**Comment by ebocher** [comment]
Dear @jixuan-chen ,

It rocks ! thanks a lot. Below a result on the french city Nantes.

![target](https://github.com/user-attachments/assets/2921cd1c-310d-4380-ae21-dbe7daa8c17f)

Some cells have a very high average TA. It seems due to the roof fraction and the W indicators. Does it make sense to filter this kind of cells in the Py code and apply a rule when the W is very low ? 

![Capture d’écran du 2024-12-16 11-08-41](https://github.com/user-attachments/assets/0884eea2-5bec-449d-a95b-d7aba70e1c7b)

**Comment by ebocher** [comment]
For documentation purposes, another case with the roof formatted at 0.75 and the W calculated with the formula : grid_resolution*(1-roof)

![Capture d’écran du 2024-12-16 12-39-50](https://github.com/user-attachments/assets/22fc4983-9e11-42dd-833f-9ab0568ca987)

**Comment by bartpannemans** [comment]
@ebocher, I wonder if these high temperatures could be linked to the corrected roof-fraction. If this is lowered to 0.75, some other fraction should be increased, otherwise the total fraction ends up lower than 1. Probably Target is not handling this well. 

I tested this for your second example, 
In a run with total fraction <1, Target indeed gives no warnings. 
In a second run I increased parameter _conc_ from 0.07 to 0.25 (but of course you could probably also choose to increase parameter _road_). The resulting temperatures are considerably lower than in the first run.

![Image](https://github.com/user-attachments/assets/4b62fc5c-e725-4ae0-924a-6b77d55ebf14)

[input_issue14_rooffraction075.zip](https://github.com/user-attachments/files/19468067/input_issue14_rooffraction075.zip)
